module.exports = {
  projects: [
    '<rootDir>/apps/api',
    '<rootDir>/apps/api-e2e',
    '<rootDir>/libs/api/auth/data-access',
    '<rootDir>/libs/api/auth/feature',
    '<rootDir>/libs/api/core/data-access',
    '<rootDir>/libs/api/core/feature',
    '<rootDir>/apps/web',
    '<rootDir>/libs/web/assets',
    '<rootDir>/libs/web/auth/data-access',
    '<rootDir>/libs/web/core/data-access',
    '<rootDir>/libs/web/about/feature',
    '<rootDir>/libs/web/auth/feature',
    '<rootDir>/libs/web/core/feature',
    '<rootDir>/libs/web/dashboard/feature',
    '<rootDir>/libs/web/shell/feature',
    '<rootDir>/libs/web/layout',
    '<rootDir>/libs/web/style',
    '<rootDir>/libs/web/ui-form',
  ],
}
